### ISSUE TITLE
Websocket change

### ISSUE THREAD

**Issue by OrbitApoapsis** [FuzzyWords/FinitPy#11]
I'm not too familiar on how to properly format addresses for the websocket library, so I'll just state what's changed.

The address has been changed. So, on finitclient.py Line 50, the current address needs to be replaced with the properly formatted version of:
`https://ws.finit.co/?authPath=/api/websockets/auth&instance_id=&token=`

**Comment by FuzzyWords** [comment]
It should be fixed now.
